### ISSUE TITLE
$(( $(x) ... )) highlighting has different scopes than $(x)

### ISSUE THREAD

**Issue by michaelblyons** [jfcherng/Sublime-ShellScriptImproved#12]
There is highlighting for both of these lines, but it is inconsistent:

``` bash
changed=$(echo "$gitstatus" | egrep "^ [MR]" | wc -l)
plus=$(($(echo "$gitstatus" | egrep "^[ C]A" | wc -l) + $(echo "$gitstatus" | egrep "^\?\?" | wc -l)))
```

Scopes are different for:
- `echo`, `egrep`,  `wc` (probably all the same rule)
- the `egrep`'s match text
- the `wc`'s `-l` flag

**Comment by jfcherng** [comment]
Should be resolved by b0240edd5beae0824757c7d8e4edb50d4423ca4a.
