### ISSUE TITLE
The += operator and strings beginning with spaces

### ISSUE THREAD

**Issue by michaelblyons** [jfcherng/Sublime-ShellScriptImproved#13]
The `+=` operator is not recognized as an operator. Also, if you attempt to concatenate strings beginning with spaces, the string delimiting is broken for the rest of the file.

``` sh
foo="bar"
#  ^      keyword.operator.assignment
#    ^^^  string.quoted.double
foo+=" baz"
# ^^^^^^^^ source.shell - keyword
#          ^^^^ string.quoted.double
```

**Comment by jfcherng** [comment]
Thanks. This should be fixed by c08ec48ebabedff9f936fb9175d11c32f798f3cd.
