### ISSUE TITLE
$(), `` and $(()) are still matched by the ‘String’ scope

### ISSUE THREAD

**Issue by ghost** [jfcherng/Sublime-ShellScriptImproved#14]
I’ve copied the lacking scope settings to my theme, but alternating the style for `$(…)`,  ``…`` and `$((…))` doesn’t work. Variables, for example, are matched as `variable.other.brackets.shell`, and there’s no problem. As well as with the keywords and special shell directives as `set` or `declare`.

I’ve tried to move the additional scope settings below and above the definition of the String scope, but it didn’t have an effect.

The same happens, when your original dark theme is selected. Those parts in the syntax test shell script aren’t highlighted properly and are identified as just strings. 

Interesting thing is that ColorSchemeEditor shows in status line five scopes, which end on `string.interpolated.backtick.shell`, while switching between scopes with `Ctrl+Alt+→` will show six:
`string > meta.reset.color > variable.other.bracket.shell (×2) > variable (×2)`

I have sublime-text-3114. 

![1468939952](https://cloud.githubusercontent.com/assets/2245254/16954476/0f93a018-4de2-11e6-8f84-4bf2beb1b2a4.png)

**Comment by jfcherng** [comment]
I thought this is a bug of ST in color scope selecting.
https://forum.sublimetext.com/t/new-rule-in-color-scheme-doesnt-match-what-i-expected/21189
https://forum.sublimetext.com/t/repeated-nesting-of-scopes-resulting-in-wrong-syntax-highlighting/20938

The most early topic about this is about in 2003 in my poor memory so I don't think it would be fixed.

**Comment by ghost** [comment]
Thanks for the response, but do you have any idea, why may this happen? I have a clear installation, and I see that ShellScriptImproved doesn’t highlight syntax as it does on your screenshots from this repo. I’d like to find the difference between yours installation and mine to figure out what may be the issue. 

I’ve tried to downgrade Sublime to 3103, but the problem persists even in the older version. You’ve stated, that ShellScriptImproved works only with version >=3093, and that means there’s no other choice left for me, since in my distro’s repository are only v3083 and older, no 309x at all. What would you suggest?

**Comment by jfcherng** [comment]
Could you show a screenshot with my dark theme?

**Comment by ghost** [comment]
Sure.

![1468948250](https://cloud.githubusercontent.com/assets/2245254/16959350/b5ac5b8a-4df5-11e6-874e-a24c5456af20.png)

Now I see, that I must have mistaken something when looking at the first time, since your theme still looks as it should be, despite that ColorSchemeEditor stucks on `meta.reset.color`. I feel like I picked a wrong theme to develop mine upon, he-he. Thanks, I think that the issue is solved.
