### ISSUE TITLE
Quantifier inappropriately matched as invalid

### ISSUE THREAD

**Issue by ghost** [jfcherng/Sublime-ShellScriptImproved#15]
In an expression like this `[[ " x " =~ \ ?[a-z]\  ]]` where an escaped space precedes the quantifier `?`, the question mark gets matched as invalid.illegal.unexpected-quantifier.regexp, though it isn’t.

![1469109339](https://cloud.githubusercontent.com/assets/2245254/17025330/66e1a51e-4f6c-11e6-9478-4df4bba8ec8e.png)

![1469109049](https://cloud.githubusercontent.com/assets/2245254/17025252/229b605c-4f6c-11e6-9cf9-805daea591a0.png)

**Comment by jfcherng** [comment]
Thanks. This should be fixed in `1.2.6`.
