### ISSUE TITLE
Add a scope for variables on assignment

### ISSUE THREAD

**Issue by ghost** [jfcherng/Sublime-ShellScriptImproved#17]
It would be nice to have a scope to match variables in assignment clauses. 
![1469182795](https://cloud.githubusercontent.com/assets/2245254/17054429/318f46da-5018-11e6-8aa1-e73f114fbc6a.png)

**Comment by jfcherng** [comment]
Add `meta.variable.assigned.shell` as the scope for some simple cases in `1.2.11`.
