### ISSUE TITLE
String scope gets broken on array element assignment

### ISSUE THREAD

**Issue by ghost** [jfcherng/Sublime-ShellScriptImproved#18]
In an expression like this

``` bash
    foo[bar]="`<$file`"
```

The first double quote isn’t opening the string scope, matches simply as source.shell.

``` bash
    foo="`<$file`"
```

and

``` bash
    foo[bar]="$(<$file)"
```

both do not show this issue.

**Comment by jfcherng** [comment]
Fixed by f1028f765916c1af34c87ce65519eeba2558dde0.
