### ISSUE TITLE
Multiline string after herestring isn’t matching properly

### ISSUE THREAD

**Issue by ghost** [jfcherng/Sublime-ShellScriptImproved#19]
If the string on the second or one of the next lines has more than one word, i.e. separated with spaces, it starts to mess everything
![1470187047](https://cloud.githubusercontent.com/assets/2245254/17350662/a3f15f2c-5939-11e6-8ab6-f7b23fda14f3.png)

The lines that should be matched as a string, match only `source.shell` at the beginning of line, and `source.shell > meta.reset.color` after a space, if it’s present.

**Comment by jfcherng** [comment]
Thanks. This should be fixed by 34d9a5c9cb8232023564a21998d31f08373fae68.
