### ISSUE TITLE
The scope is improper after heredoc

### ISSUE THREAD

**Issue by jfcherng** [jfcherng/Sublime-ShellScriptImproved#2]
![image](https://cloud.githubusercontent.com/assets/6594915/14346157/6fd974c0-fce3-11e5-91f2-380d1b6ef8f7.png)

As described in https://github.com/jfcherng/Sublime-ShellScriptImproved/issues/1#issuecomment-206750685.

**Comment by jfcherng** [comment]
Related post: https://forum.sublimetext.com/t/how-to-deal-with-partially-overlapping-context/19122

**Comment by jfcherng** [comment]
Should be resolved in 1.0.12.

**Comment by dasisdormax** [comment]
Hello once again. Nice that you could do it, however your fix brought two new issues regarding normal "boring" syntax.

First: An indented (with tabs) EOF is no longer detected

``` bash
    cat <<-EOF
            This is some text
        EOF
```

Second: if the heredoc starts on such a line, it actually demands the closing } or fi. See for example:

``` bash
fun () { cat <<EOF
    Some text with a curly bracket }
    Some text with a semicolon and a curly bracket; }
    Even more text
EOF
}
```

So you should return to the normal heredoc context when hitting the newline or something like that

**Comment by jfcherng** [comment]
@dasisdormax Nice catch.

The first one is actually an accident. A space indentation before `EOF` raised a warning but I thought it is an error at that time. I will revert the commit in the next release.

The second one will be fixed in the next release.
