### ISSUE TITLE
Equal sign (=) breaks backticks’ subshell interpolation scope

### ISSUE THREAD

**Issue by ghost** [jfcherng/Sublime-ShellScriptImproved#20]
If an equal sign is within the backticks, and it isn’t prepended with backslash or taken inside quotes, it breaks the subshell interpolation scope of the backticks, and the scope continues till the end of the file.

``` bash
func() {
    disk=`findfs UUID=00000000-0000-0000-0000-001234567891 2>/tmp/findfs_err` && {
        mkdir /mnt/disk
        mount $disk !$ || err cant_mount
    }
    return 0
}
```

![1470630941](https://cloud.githubusercontent.com/assets/2245254/17469485/923cf9e4-5d44-11e6-9b82-352dd22eea93.png)

![1470631317](https://cloud.githubusercontent.com/assets/2245254/17469499/c6352c1c-5d44-11e6-8b6f-81b61a0a2dd1.png)

This doesn’t happen if the construction `$()` is used for a subshell.

![1470630925](https://cloud.githubusercontent.com/assets/2245254/17469490/959b1e2c-5d44-11e6-85b5-12f663919264.png)

**Comment by jfcherng** [comment]
Thanks. Fixed by d2cdc0b737e4735c8749bab05b1d7387fd038ce0.
