### ISSUE TITLE
Variable scope ends on first underscore in expansions

### ISSUE THREAD

**Issue by ghost** [jfcherng/Sublime-ShellScriptImproved#21]
If a variable name starts with an underscore, only the `$_` part is matched as a variable.

![1470632135](https://cloud.githubusercontent.com/assets/2245254/17469639/05f0e106-5d46-11e6-9ca4-25d6be73a725.png)

**Comment by jfcherng** [comment]
Thanks. Fixed by 91eeeabdd2880d3a211b1d9cbc01bb0376692085.
