### ISSUE TITLE
Next pattern in the case statement isn’t matched as case-pattern if previous clause ended with ;&

### ISSUE THREAD

**Issue by ghost** [jfcherng/Sublime-ShellScriptImproved#22]
The ;& operator, telling the case statement to also apply the next clause, breaks the case-pattern scope for the next pattern. This doesn’t happen, when a clause ends on `;;` or `;;&`.

``` bash
case "$stage" in
    preparation) ;&
    download) ;&
    check) ;&
    activation) ;;
esac
```

![1470632431](https://cloud.githubusercontent.com/assets/2245254/17469769/8f650e52-5d47-11e6-8446-7ae252fa5aec.png)
![1470632462](https://cloud.githubusercontent.com/assets/2245254/17469776/98409bea-5d47-11e6-8e88-bfb340ac2202.png)
![1470632821](https://cloud.githubusercontent.com/assets/2245254/17469781/a1a9d700-5d47-11e6-9b9d-5f7e25a2c29a.png)

**Comment by jfcherng** [comment]
Thanks. Fixed by a48c1b5b846108b0fa6a51f364b9b37e58087166.
