### ISSUE TITLE
case statement indentation is broken in 1.2.9

### ISSUE THREAD

**Issue by ghost** [jfcherng/Sublime-ShellScriptImproved#24]
After the first case-pattern indentation drops to zero till `esac`.

``` bash
    case "$branch" in
        master)
# To change version in the isolinux.cfg
release=t
;;
HEAD)
branch='DETACHED'
;;
*)
;;
esac
```

![1471004987](https://cloud.githubusercontent.com/assets/2245254/17622308/8acda9ce-60aa-11e6-80d8-369ac3dde008.png)

**Comment by jfcherng** [comment]
Do you mean ST's auto-indent fails?

**Comment by ghost** [comment]
I’m not sure. I press TAB on a line where the comment on the picture above should be, and it moves the code to the very left. I try to select all the clause and press TAB – and see what’s on the picture. I’m sorry if it has nothing to do with ShellScriptImproved, I’d just expect the mode to control indentation after experience with Emacs.

**Comment by jfcherng** [comment]
> I press TAB on a line where the comment on the picture above should be, and it moves the code to the very left.

![gif](https://cloud.githubusercontent.com/assets/6594915/17623714/f0509af8-60d3-11e6-87fd-0057c11f93e8.gif)

Can't reproduce?
- Clean ST 3120 Portable
- Win7 x64

## 

Could you reproduce it with a clean portable ST which only installs `Package Control` and `ShellScriptImproved`?

**Comment by ghost** [comment]
No, I can’t. Actually, when I press TAB on a line below it becomes aligned with `case`, and the lines below it become aligned this way. On the webm below I select the unindented text and press TAB to perform autoindent of this region, then I put cursor to each line and press TAB twice. 

http://webm.land/media/tmp/570d7621-d455-4b87-9214-5f2b9c4d4863.webm

Here are my settings related to the TAB key.

```
"auto_complete": false,
"auto_complete_commit_on_tab": false,
"auto_complete_cycle": false,
"auto_complete_delay": 50,
"auto_complete_selector": "meta.tag - punctuation.definition.tag.begin, source - comment - string.quoted.double.block - string.quoted.single.block - string.unquoted.heredoc",
"auto_complete_size_limit": 4194304,
"auto_complete_triggers":
[
    {
        "characters": "<",
        "selector": "text.html"
    }
],
"auto_complete_with_fields": false,
"auto_find_in_selection": false,
"auto_indent": true,
"tab_completion": true,
"use_tab_stops": true,
```

**Comment by jfcherng** [comment]
I guess `ShellScriptImproved` has nothing to do with auto-indent issues since it currently only contains a `.sublime-syntax` file. Just tried ST's `ShellScript (Bash)` and `ShellScriptImproved 1.2.7` and none of them works.

**Comment by ghost** [comment]
Sorry, then.
