### ISSUE TITLE
incorrect highlighting in bash array

### ISSUE THREAD

**Issue by t-bltg** [jfcherng/Sublime-ShellScriptImproved#25]
Hey,

when I issue this in a bash script:

``` bash
OPTS+=(--prefix=$PREFIX)
```

then $PREFIX is not highlighted ...

Any clues on how to fix this ?

Thanks

**Comment by jfcherng** [comment]
This should be resolved in [1.2.10](https://github.com/jfcherng/Sublime-ShellScriptImproved/releases/tag/1.2.10).
