### ISSUE TITLE
Highlighting Broken After Array Index

### ISSUE THREAD

**Issue by stevekuznetsov** [jfcherng/Sublime-ShellScriptImproved#28]
In [`hack/lib/log/stacktrace.sh`](https://github.com/openshift/origin/blob/master/hack/lib/log/stacktrace.sh#L61) we have the following:

``` sh
        if [[ ! "${BASH_SOURCE[${stack_begin_index}]}" =~ hack/lib/(log/stacktrace|util/trap)\.sh ]]; then
            break
        fi
```

This highlights poorly:
![index](https://cloud.githubusercontent.com/assets/7328370/19195340/36a2d9fe-8c7f-11e6-8d0c-7d5bc761ebda.png)

When the array index is a var that is getting expanded, the closing braces get flagged as a string.

**Comment by jfcherng** [comment]
It looks like that this issue is fixed in `1.12.11` too. So I am going to close it.
