### ISSUE TITLE
Enhancement: Add support for zsh parameter expansion flags

### ISSUE THREAD

**Issue by okdana** [jfcherng/Sublime-ShellScriptImproved#31]
From [`zshexpn(1)`](http://zsh.sourceforge.net/Doc/Release/Expansion.html#Parameter-Expansion-Flags):

> If the opening brace is directly followed by an opening parenthesis, the string up to the matching closing parenthesis will be taken as a list of flags.

Here are some simple examples:

```
: "${(L)foo}"     # Lower-case foo, equivalent to ${foo,,} in bash
: "${(@)foo}"     # Separate elements of foo, equivalent to ${foo[@]}
: "${(uU)foo[@]}" # Filter foo for unique elements and upper-case each one
: "${(%)foo}"     # Apply prompt expansion to foo
```

As far as i know it's not legal to use `(...)` after the opening brace in any other shell, so adding this should produce few if any syntax conflict issues.

For the scope i would suggest something in the `keyword.operator.*.shell` family, to match other parameter-expansion meta-characters.

**Comment by jfcherng** [comment]
I am not sure whether I am doing a right thing since this package is meant for Bash.
But it won't break the current Bash highlight and it's simple to add some basic support for this.

![image](https://cloud.githubusercontent.com/assets/6594915/19219568/0dc28220-8e49-11e6-9f0a-e3b39d12f746.png)

Things above have been added in `1.12.2`.

## 

Is this okay?

**Comment by okdana** [comment]
The last one is a little confusing. Just to be clear, your `${(ps.ps$sep.)val}` example breaks down like this:

<img width="700" alt="screen shot 2016-10-09 at 05 25 10" src="https://cloud.githubusercontent.com/assets/122095/19219724/f71c4d3e-8de0-11e6-9145-ffa16bc934df.png">

So i _think_ the only problem you have there is the second `ps`, which is not another set of flags but rather part of the 'argument' to the `s` flag.

Note that the delimiters for `s` flag and friends work like the delimiters for regular expressions in Perl/PHP, so for example all of these are valid delimiter pairs:

```
${(ps.ps$sep.)val}
${(ps:ps$sep:)val}
${(ps/ps$sep/)val}
${(ps|ps$sep|)val}
${(ps<ps$sep>)val}
${(ps(ps$sep))val} # This one is tricky
${(ps{ps$sep})val} # This too
```

If the scope is too complicated on those weird ones, i think it'd be perfectly acceptable to limit it to the simpler cases, like `\([0-9A-Za-z#%@:]+\)` or whatever

**Comment by jfcherng** [comment]
That image is beautiful. Is that made with a special tool?

## 

> The last one is a little confusing. Just to be clear,

Yes, I admit the second `ps` is confusing. The second `ps` here is just for test purpose to make sure it's not classified as flags.

## 

> If the scope is too complicated on those weird ones, i think it'd be perfectly acceptable to limit it to the simpler cases, like ([0-9A-Za-z#%@:]+) or whatever

I add all flags found in the doc you provided. For simplicity, no further grammar is parsed. I.e., I only add scopes for flags.

https://github.com/jfcherng/Sublime-ShellScriptImproved/commit/f58492bee25620a3dbd6a0a84fcba3749f878d4c#diff-c246dd8ca6aeffd8d5d38a0d34be214aR1203

## 

> ${(ps.ps$sep.)val}
> ${(ps:ps$sep:)val}
> ${(ps/ps$sep/)val}
> ${(ps|ps$sep|)val}
> ${(ps<ps$sep>)val}
> ${(ps(ps$sep))val} # This one is tricky
> ${(ps{ps$sep})val} # This too

I can enumerate some common delimiters that you list here.

**Comment by okdana** [comment]
Sounds good!

**Comment by jfcherng** [comment]
![image](https://cloud.githubusercontent.com/assets/6594915/19220039/a931cdb2-8e56-11e6-8692-f8269bc39b0f.png)

Now it should be okay in `1.2.13`.

## 

`punctuation.definition.delimiter.begin.shell` and `punctuation.definition.delimiter.end.shell`
are added to scope regex delimiters.

``` bash
${(ps(ps$sep))val}
# ^ punctuation.definition.flag.begin.shell
#  ^^ keyword.operator.expansion.flag.shell
#    ^ punctuation.definition.delimiter.begin.shell
#     ^^ - keyword.operator.expansion.flag.shell
#       ^^^^ variable.other.normal.shell
#           ^ punctuation.definition.delimiter.end.shell
#            ^ punctuation.definition.flag.end.shell
```

**Comment by okdana** [comment]
Neat. Thanks again! 👍
