### ISSUE TITLE
Doesn't support command-line options with '+' prefix

### ISSUE THREAD

**Issue by okdana** [jfcherng/Sublime-ShellScriptImproved#32]
It's not super common, but some utilities use `+` as a command-line switch prefix instead of or in addition to `-`. The one i use most commonly is `dig`, but `bash` and `lsof` also do it, and i know that Python's `argparse` supports it (though i don't know of any Python tools that use it off the top of my head).

Test case:

```
dig example.com +short +time=3 +tries=3
dig example.com -short -time=3 -tries=3
```

Result:

![screen shot 2016-10-14 at 16 11 03](https://cloud.githubusercontent.com/assets/122095/19403126/ba44c97e-922a-11e6-9bb2-43dc5967967a.png)

Context of the `+` ones is `meta.variable.assigned.shell`; context of the `-` ones is `support.command-switch.shell`.

Not a big deal, but it'd be nice if they were the same. I think just `command_switch.match` needs updated, but i didn't test it.

**Comment by jfcherng** [comment]
Thanks. It should be resolved by https://github.com/jfcherng/Sublime-ShellScriptImproved/commit/f9a3589360ed93a2153ff6c5b5ffdc72fd4804d7.

**Comment by okdana** [comment]
Thanks again!
