### ISSUE TITLE
Bash colored as string in a when using indirect reference and array default values

### ISSUE THREAD

**Issue by andyneff** [jfcherng/Sublime-ShellScriptImproved#33]
A command like `TEMP_VAR=(${!default+"${!default}"})` causes the syntax highlighting to detect everything afterwards as an open string

`TEMP_VAR=(${default+"${!default}"})` works
`TEMP_VAR=(${!default+${!default}})` works
`TEMP_VAR=(${!default"}"})` Does not work, but isn't really valid bash anymore. Just showing it's the !,}, and " not getting along causing this bug

![image](https://cloud.githubusercontent.com/assets/7596961/19459562/e2e38450-94a1-11e6-8f20-e61a7534bca5.png)

Using Sublime 3 build 3126 and ShellScript Improved 1.2.14, it happened in 1.2.13 too. It may not be a new bug

**Comment by jfcherng** [comment]
Thanks. It should be fixed in `1.2.15`.
