### ISSUE TITLE
Associative arrays with dashes in keys

### ISSUE THREAD

**Issue by anlutro** [jfcherng/Sublime-ShellScriptImproved#38]
```bash
declare -A outputs
outputs[HDMI1] = "--auto"
outputs[HDMI-1] = "--auto"
```

The former is fine, the second is not.

Furthermore, if you try to assign a value that has spaces in it, it really messes up your syntax highlighting:

```bash
outputs[HDMI-1]=" "
# syntax broken from now on
echo "hello world "
```

**Comment by jfcherng** [comment]
Thanks. Should be fixed in `1.2.22`.
