### ISSUE TITLE
Invalid syntax test

### ISSUE THREAD

**Issue by rwols** [jfcherng/Sublime-ShellScriptImproved#39]
I was staring at this for a very long time: https://github.com/jfcherng/Sublime-ShellScriptImproved/blob/master/syntax_test_shellscript.sh#L835-L838

But the test is wrong... This invokes the command "echo-e", so the "-e" should not be a switch.

Here is the same idea:
```bash
#!/bin/bash
# prints "hello"
e\
c\
h\
o\
 \
h\
e\
l\
l\
o
```

The other tests around it are correct.

**Comment by jfcherng** [comment]
Ah, nice catch. Has corrected that in https://github.com/jfcherng/Sublime-ShellScriptImproved/commit/f5d7548e968d58d4e7f1611e1cf8d3034731e8ba. 

---

But then there is a fail test though lol. And that looks tricky to deal with.
