### ISSUE TITLE
$(( ... )) highlighting incorrect w/ nested brackets & variables

### ISSUE THREAD

**Issue by zx8** [jfcherng/Sublime-ShellScriptImproved#4]
**Example 1:** Brackets highlighting incorrectly
<img width="276" alt="example_1" src="https://cloud.githubusercontent.com/assets/8544900/14403750/2803d702-fe5b-11e5-8c6e-0a64d2c63197.png">

**Example 2**: Variable `RANDOM` highlighted as string
<img width="324" alt="example_2" src="https://cloud.githubusercontent.com/assets/8544900/14403751/28048e40-fe5b-11e5-9aaa-16d75cb060be.png">

(Note: Example 2 is a special case, since `$` is not required before variable names inside `$((...))`)

**Comment by jfcherng** [comment]
It looks like this is introduced while fixing [this](https://forum.sublimetext.com/t/bash-syntax-hightlighting-error/12820). Not sure how to deal with both that issue and this issue now.

The following command gives a more general case for **Example 1** which could involve parenthesis balancing issue. Github highlights it wrongly as well.

``` bash
echo $(( (2*(4+1))/5 ))
```

![image](https://cloud.githubusercontent.com/assets/6594915/14404827/20060528-feb2-11e5-8161-a61643472fb9.png)

**Comment by jfcherng** [comment]
This should be resolved in 1.0.14.

![image](https://cloud.githubusercontent.com/assets/6594915/14404807/971fe8be-feb1-11e5-85fd-fbee3c29e6bf.png)

With adding `variable.other.c-style.shell` to the color scheme.

``` xml
<dict>
    <key>name</key>
    <string>Shell - variable</string>
    <key>scope</key>
    <string>variable.other.normal.shell, variable.other.positional.shell, variable.other.bracket.shell, variable.other.special.shell, variable.other.c-style.shell</string>
    <key>settings</key>
    <dict>
        <key>fontStyle</key>
        <string>bold</string>
        <key>foreground</key>
        <string>#AE81FF</string>
    </dict>
</dict>
```

**Comment by michaelblyons** [comment]
There is highlighting for both of these lines, but it is inconsistent:

``` bash
changed=$(echo "$gitstatus" | egrep "^ [MR]" | wc -l)
plus=$(($(echo "$gitstatus" | egrep "^[ C]A" | wc -l) + $(echo "$gitstatus" | egrep "^\?\?" | wc -l)))
```

Scopes are different for:
- `echo`, `egrep`,  `wc` (probably all the same rule)
- the `egrep`'s match text
- the `wc`'s `-l` flag

If you want, I can open a new issue, instead.

**Comment by jfcherng** [comment]
@michaelblyons Yes, please open another issue for that.
