### ISSUE TITLE
true and false bash constant not highlighted

### ISSUE THREAD

**Issue by kkew3** [jfcherng/Sublime-ShellScriptImproved#41]
Version:  1.2.28

Unquoted `true` and `false`, according to bash help, are shell builtins that successful and unsuccessful result respectively. However, it seems that they are treated the same as ordinary strings.

<img width="173" alt="Screen Shot 2019-03-27 at 8 46 12 PM" src="https://user-images.githubusercontent.com/13264071/55128625-70a8ac00-50d1-11e9-96d1-6361edd382b0.png">

**Expected behavior**: *unquoted* `true` and `false` are colored in, e.g. purple, so that they are different from ordinary strings

**Comment by jfcherng** [comment]
It's working as shown in the screenshot in the README.
But your color scheme just doesn't define colors for those scopes.

---

And as written in the README, you can either
- [use my color scheme](https://github.com/jfcherng/Sublime-ShellScriptImproved#color-scheme)

or 

- [modify your color scheme](https://github.com/jfcherng/Sublime-ShellScriptImproved#customization-from-your-color-scheme)

---

Again, this package has been deprecated, i.e., not maintained. You may want to use the built-in shellscript syntax highlight, it's much better than it was before.
