### ISSUE TITLE
Variables following ! operator within [ ... ] not highlighted

### ISSUE THREAD

**Issue by zx8** [jfcherng/Sublime-ShellScriptImproved#9]
The `$foo` variable on the first 2 lines should be highlighted, the last line is correct:

<img width="289" alt="variable-not-operator" src="https://cloud.githubusercontent.com/assets/8544900/15001407/20ff557a-118f-11e6-9cee-5e863dbc7da3.png">

**Comment by jfcherng** [comment]
Should be resolved by 680e0969304caeb8c6262d37654d1f4996a770bb.
